name: Run Java Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java (use the version that suits your project)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      # Build the project and run tests using Maven (or Gradle if that's what you're using)
      - name: Run tests with Maven
        run: |
          mvn clean test -Dtest=com.example.AppTest
